site_name: 1391 Self Training for FRC
theme:
  name: material
  favicon: 'imgs/favicon.png'
  logo: 'imgs/logo.png'
  palette:
    primary: red

  

nav:
  - Home: index.md
  - General Information: general.md
  - Design + Build:
    - Overview: design/index.md
    - CAD Learning: design/cad/index.md
    - Reading: design/reading.md
    - Videos: design/videos.md
    - Mini Projects: design/mini.md
  - Programming:
    - Overview: programming/index.md
    - Java Learning: programming/java.md
    - Reading: programming/reading.md
    - Videos: programming/videos.md
    - Mini Projects: programming/mini.md
  - Electrical: 
    - Overview: electrical/index.md
    - Components: electrical/components.md
    - Reading: electrical/reading.md
    - Videos: electrical/videos.md
    - Mini Projects: electrical/mini.md
  - Strategy: 
    - Overview: strategy/index.md
    - Scouting: strategy/scouting.md
    - Reading: strategy/reading.md
    - Videos: strategy/videos.md
    - Mini Projects: strategy/mini.md
  - About 1391: team.md





extra_css:
  - assets/main.css

extra_javascript:
  - assets/main.js
