site_name: 1391 Self Training
theme:
  name: material
  favicon: 'imgs/favicon.png'
  logo: 'imgs/logo.png'
  palette:
    primary: red

  

nav:
  - Home: index.md
  - General Information: general.md
  - Design + Build:
    - Overview: design/index.md
    - CAD Learning: design/cad.md
    - Reading: design/reading.md
    - Videos: design/videos.md
    - Mini Projects: design/mini.md
  - Programming: programming.md
  - Electrical: electrical.md
  - Strategy: strategy.md
  - About 1391: team.md




extra_css:
  - extra.css


